// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSosjltFW11ltvV5vggPKT1FZDylcoER0',
    appId: '1:904393828484:web:a2e0159ef789587bf93ad1',
    messagingSenderId: '904393828484',
    projectId: 'smart-pos-7c76c',
    authDomain: 'smart-pos-7c76c.firebaseapp.com',
    storageBucket: 'smart-pos-7c76c.firebasestorage.app',
    measurementId: 'G-SZ9GHBZ3WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: '904393828484',
    projectId: 'smart-pos-7c76c',
    storageBucket: 'smart-pos-7c76c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '904393828484',
    projectId: 'smart-pos-7c76c',
    storageBucket: 'smart-pos-7c76c.firebasestorage.app',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: '904393828484',
    projectId: 'smart-pos-7c76c',
    storageBucket: 'smart-pos-7c76c.firebasestorage.app',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSosjltFW11ltvV5vggPKT1FZDylcoER0',
    appId: '1:904393828484:web:a2e0159ef789587bf93ad1',
    messagingSenderId: '904393828484',
    projectId: 'smart-pos-7c76c',
    authDomain: 'smart-pos-7c76c.firebaseapp.com',
    storageBucket: 'smart-pos-7c76c.firebasestorage.app',
    measurementId: 'G-SZ9GHBZ3WC',
  );
}