// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSosjltFW11ltvV5vggPKT1FZDylcoER0',
    appId: '1:904393828484:web:08023959fdd53596f93ad1',
    messagingSenderId: '904393828484',
    projectId: 'smart-pos-7c76c',
    authDomain: 'smart-pos-7c76c.firebaseapp.com',
    storageBucket: 'smart-pos-7c76c.firebasestorage.app',
    measurementId: 'G-MD2BWSR6J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-IP6TUrrcMPng_7QYMUUYLLu1v2t53aY',
    appId: '1:904393828484:android:3813bb07f87ec866f93ad1',
    messagingSenderId: '904393828484',
    projectId: 'smart-pos-7c76c',
    storageBucket: 'smart-pos-7c76c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYO2QW6GKGr-Ehyz6qOVAhbLi3O3Kkm_Y',
    appId: '1:904393828484:ios:b1f337e554686107f93ad1',
    messagingSenderId: '904393828484',
    projectId: 'smart-pos-7c76c',
    storageBucket: 'smart-pos-7c76c.firebasestorage.app',
    iosClientId: '904393828484-9fkroh4vgt4f3et4r49j2pgn1nov9vv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYO2QW6GKGr-Ehyz6qOVAhbLi3O3Kkm_Y',
    appId: '1:904393828484:ios:823395644d973194f93ad1',
    messagingSenderId: '904393828484',
    projectId: 'smart-pos-7c76c',
    storageBucket: 'smart-pos-7c76c.firebasestorage.app',
    iosClientId: '904393828484-vs1qbdes5ce8mnrh881hqsglh2ksaoo7.apps.googleusercontent.com',
    iosBundleId: 'com.smartpos.smartPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSosjltFW11ltvV5vggPKT1FZDylcoER0',
    appId: '1:904393828484:web:4211115e123d8bb9f93ad1',
    messagingSenderId: '904393828484',
    projectId: 'smart-pos-7c76c',
    authDomain: 'smart-pos-7c76c.firebaseapp.com',
    storageBucket: 'smart-pos-7c76c.firebasestorage.app',
    measurementId: 'G-TTQG2BVC41',
  );

}